---
version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - '10001:8080'
    volumes:
      - './mount/jenkins_home:/var/jenkins_home'
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - tools
  nexus:
    image: sonatype/nexus3
    ports:
      - '10002:8081'
    volumes:
      - './mount/nexus-data:/nexus-data'
    networks:
      - tools
networks:
  tools: