---
# command + shift + / 
version: '3'
services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - '10001:8080'
    volumes:
      - '/Users/samitkumarpatel/mount/jenkins_home:/var/jenkins_home'
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    networks:
      - tools
  # nexus:
  #   image: sonatype/nexus3
  #   ports:
  #     - '10002:8081'
  #   volumes:
  #     - '/Users/samitkumarpatel/mount/nexus-data:/nexus-data'
  #   networks:
  #     - tools
  # sonarqube:
  #   image: sonarqube
  #   ports:
  #     - "10003:9000"
  #   networks:
  #     - sonarnet
  #   environment:
  #     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
  #     - SONARQUBE_JDBC_USERNAME=sonar
  #     - SONARQUBE_JDBC_PASSWORD=sonar
  #   volumes:
  #     - /Users/samitkumarpatel/mount/sonarqube_conf:/opt/sonarqube/conf
  #     - /Users/samitkumarpatel/mount/sonarqube_data:/opt/sonarqube/data
  #     - /Users/samitkumarpatel/mount/sonarqube_extensions:/opt/sonarqube/extensions
  #     - /Users/samitkumarpatel/mount/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  # db:
  #   image: postgres
  #   networks:
  #     - sonarnet
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #   volumes:
  #     - /Users/samitkumarpatel/mount/postgresql:/var/lib/postgresql
  #     - /Users/samitkumarpatel/mount/postgresql_data:/var/lib/postgresql/data
networks:
  tools:
  # sonarnet: